[04 数据操作 + 数据预处理【动手学深度学习v2】](https://www.bilibili.com/video/BV1CV411Y7i4?spm_id_from=333.999.0.0)

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

x里面标量的数量

In [4]:
x.numel()

12

In [5]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [8]:
x = torch.arange(12).reshape(3,4)
y = x**2

In [9]:
torch.cat((x,y),dim=0)

tensor([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])

In [10]:
torch.cat((x,y),dim=1)

tensor([[  0,   1,   2,   3,   0,   1,   4,   9],
        [  4,   5,   6,   7,  16,  25,  36,  49],
        [  8,   9,  10,  11,  64,  81, 100, 121]])

In [11]:
x == y

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()

tensor(66)

[numpy广播机制](https://www.runoob.com/numpy/numpy-broadcast.html)

In [13]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [15]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [16]:
x[1,2]

tensor(6)

减少内存开销

In [17]:
before = id(x)
x +=y
id(x) == before

True

与numpy之间的相互转换

In [18]:
a = x.numpy()
a

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [19]:
torch.tensor(a)

tensor([[  0,   2,   6,  12],
        [ 20,  30,  42,  56],
        [ 72,  90, 110, 132]])

In [20]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

计算机中矩阵的乘法定义为哈达吗积，即直接进行元素相乘

In [21]:
x*y

tensor([[    0,     2,    24,   108],
        [  320,   750,  1512,  2744],
        [ 4608,  7290, 11000, 15972]])

- 数学中的乘积定义如下

In [22]:
x@y.T

tensor([[  134,   854,  2214],
        [  702,  5326, 14686],
        [ 1718, 13830, 38870]])

In [23]:
a = 2
a+x,a*x

(tensor([[  2,   4,   8,  14],
         [ 22,  32,  44,  58],
         [ 74,  92, 112, 134]]),
 tensor([[  0,   4,  12,  24],
         [ 40,  60,  84, 112],
         [144, 180, 220, 264]]))

In [24]:
A = torch.arange(20*2).reshape(2,5,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

- 个人理解，n维数组是一个从外向内包裹的一个过程，比如一个数组shape为[2,3,4],那么依次对应axis=0,1,2三种情况
- 但是数组是从外向内包裹的，所以axis=0 也是就2是最外面为2，也就是2个3行4列矩阵叠加形成
- 具体的包裹方式：第一层最简单，就是数组，这是最里层，然后是外层，对应的axis的最大值，也就是按行叠加，此时形成的就是矩阵，对应着axis的次大值。
- A为2,5,4，矩阵，那么就意味着A的最外围是2
- A.sum(dim=0)就意味着最外围求和，形成的是，相当于两个5行4列的矩阵相加

In [25]:
A.sum(dim=0)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [26]:
# 同理，A.sum(dim=1),对应的是次大层，此时将按行求和
# 按行求和后，axis=2对应的4依旧为最里层，此时每行依旧为4
# 但是axis=0 对应的最外层将变列值，此时将变成2行，4列矩阵
A.sum(dim=1)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [27]:
# axis = 2 的情况就是最里层也就是数组行的求和
# 此时axis=1也就是5将变为最里层，也就是变成长度为5的数组
A.sum(dim = 2)

tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])

In [28]:
# 计算时候保持数组维数不变
# 此时可以看到数组维数保留
# 想要利用广播机制，可以采用此方法
suma = A.sum(dim=0,keepdim=True)
sumb = A.sum(dim=0)
suma,sumb

(tensor([[[20, 22, 24, 26],
          [28, 30, 32, 34],
          [36, 38, 40, 42],
          [44, 46, 48, 50],
          [52, 54, 56, 58]]]),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]))

In [29]:
# 矩阵点积是元素乘积求和
x = torch.ones(4,dtype=torch.float32)
y = x+1
torch.dot(x,y),torch.sum(x*y)

(tensor(8.), tensor(8.))

In [30]:
A = torch.arange(20).reshape(5,4)
A,x

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([1., 1., 1., 1.]))

In [31]:
a=torch.randn(2,3)
b=torch.randn(3)
a,b

(tensor([[ 0.4290, -0.2537,  0.3937],
         [ 0.3894,  1.2570, -0.8814]]),
 tensor([-0.2025,  1.5324, -1.0054]))

In [32]:
# mv为向量和矩阵的乘积
torch.mv(a,b)

tensor([-0.8714,  2.7334])

In [33]:
# mm 为矩阵与矩阵的乘积
a = torch.arange(20).reshape(5,4)
b = torch.arange(12).reshape(4,3)

In [34]:
torch.mm(a,b)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

### n范数
- 数组的i范数很好理解，就是元素的i次方求和再取i次方根
- 矩阵的i范数，就是矩阵所有元素i次方求和再取i次方根

In [35]:
a = torch.rand(20).reshape(5,4)
a

tensor([[0.3500, 0.1935, 0.9225, 0.8310],
        [0.2691, 0.9266, 0.9021, 0.2724],
        [0.0763, 0.0644, 0.5296, 0.5885],
        [0.6984, 0.9065, 0.2435, 0.9297],
        [0.6634, 0.6164, 0.7250, 0.8209]])

In [36]:
# 计算矩阵的2范数
torch.norm(a)

tensor(2.9001)